#!/usr/bin/env python

# This file is used to generate a proto representation of the Twizy for use
# with webots

import yaml
import re
import rospkg
import os
from math import pi

# Get path to twizy_description package
rospack = rospkg.RosPack()
package_path = rospack.get_path('twizy_description')

# Get path to robot properties file
yaml_filename = 'robot_properties.yaml'
yaml_file = os.path.join(package_path, 'config', yaml_filename)

# Parese YAML file
with open(yaml_file, 'r') as f:
    props = yaml.safe_load(f)


def matrix_row2str(v, *indices):
    """
    Returns a space separated string of elements of the dict or list v at
    positions specified by indices
    """

    return ' '.join(['{}']*len(indices)).format(*(v[i] for i in indices))


def vec2str(v):
    """
    Converts a vector in the form of a dict to a string for use as e.g. a
    SFVec3 in a proto file

    v is assumed to be in the ENU coodinate system, and as webots (reader of
    proto files) works in the NUE coordinate system by default, a conversion is
    needed
    """
    return matrix_row2str(v, 'y', 'z', 'x')


proto = """#VRML_SIM R2021a utf8

# ========================================================
# |    This document was autogenerated by python from    |
# |    {{'{:<50}'.format(__file__)}}|
# |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED      |
# ========================================================

PROTO Twizy [
  field SFVec3f    translation       0 0 0
  field SFRotation rotation          0 1 0 0
  field SFString   controller        "<extern>"
  field MFString   controllerArgs    [ ]
]
{
  Robot {
    physics Physics {
      density -1
      mass    {{props['chassis']['mass']}}
      centerOfMass [
        {{vec2str(props['chassis']['center_of_mass'])}}
      ]
      inertiaMatrix [
        {{matrix_row2str(props['chassis']['inertia'], 'yy', 'zz', 'xx')}}
        {{matrix_row2str(props['chassis']['inertia'], 'yz', 'xy', 'xz')}}
      ]
    }
    children [
      DEF CHASSIS Transform {
        translation 0 {{props['wheel']['radius'] + props['chassis']['height']/2.0}} 0
        children [
          Shape {
            geometry Box {
              size {{props['chassis']['track']}} {{props['chassis']['height']}} {{props['chassis']['wheelbase']}}
            }
          }
        ]
      }
      Transform {
        translation {{props['chassis']['track']/2.0}} {{props['wheel']['radius']}} {{-props['chassis']['wheelbase']/2.0}}
        rotation 0 0 1 {{pi/2.0}}
        children [
          HingeJoint {
            jointParameters HingeJointParameters {
              axis 0 1 0
            }
            device [
              RotationalMotor {
                name "rear_left_wheel_motor"
                maxTorque {{props['wheel']['max_drive_effort']}}
                sound ""
              }
            ]
            endPoint Solid {
              name "rear_left_wheel"
              children [
                DEF WHEEL_SHAPE Shape {
                  geometry Cylinder {
                    height {{props['wheel']['width']}}
                    radius {{props['wheel']['radius']}}
                    subdivision 24
                  }
                }
              ]
              boundingObject USE WHEEL_SHAPE
              physics DEF WHEEL_PHYSICS Physics {
                density -1
                mass {{props['wheel']['mass']}}
                centerOfMass [
                  {{vec2str(props['wheel']['center_of_mass'])}}
                ]
                inertiaMatrix [
                  {{matrix_row2str(props['wheel']['inertia'], 'yy', 'zz', 'xx')}}
                  {{matrix_row2str(props['wheel']['inertia'], 'yz', 'xy', 'xz')}}
                ]
              }
            }
          }
        ]
      }
      Transform {
        translation {{-props['chassis']['track']/2.0}} {{props['wheel']['radius']}} {{-props['chassis']['wheelbase']/2.0}}
        rotation 0 0 1 {{-pi/2.0}}
        children [
          HingeJoint {
            jointParameters HingeJointParameters {
              axis 0 1 0
            }
            device [
              RotationalMotor {
                name "rear_right_wheel_motor"
                maxTorque {{props['wheel']['max_drive_effort']}}
                sound ""
              }
            ]
            endPoint Solid {
              name "rear_right_wheel"
              children [
                USE WHEEL_SHAPE
              ]
              boundingObject USE WHEEL_SHAPE
              physics USE WHEEL_PHYSICS
            }
          }
        ]
      }
      Transform {
        translation {{props['chassis']['track']/2.0}} {{props['wheel']['radius']}} {{props['chassis']['wheelbase']/2.0}}
        rotation 0 0 1 {{pi/2.0}}
        children [
          Hinge2Joint {
            jointParameters HingeJointParameters {
              axis 1 0 0
            }
            jointParameters2 JointParameters {
              axis 0 1 0
            }
            device [
              RotationalMotor {
                name "front_left_hinge_motor"
                minPosition {{-props['wheel']['max_steering_angle']}}
                maxPosition {{props['wheel']['max_steering_angle']}}
                maxTorque {{props['wheel']['max_steering_effort']}}
                sound ""
              }
            ]
            endPoint Solid {
              name "front_left_wheel"
              children [
                USE WHEEL_SHAPE
              ]
              boundingObject USE WHEEL_SHAPE
              physics USE WHEEL_PHYSICS
            }
          }
        ]
      }
      Transform {
        translation {{-props['chassis']['track']/2.0}} {{props['wheel']['radius']}} {{props['chassis']['wheelbase']/2.0}}
        rotation 0 0 1 {{-pi/2.0}}
        children [
          Hinge2Joint {
            jointParameters HingeJointParameters {
              axis -1 0 0
            }
            jointParameters2 JointParameters {
              axis 0 1 0
            }
            device [
              RotationalMotor {
                name "front_right_hinge_motor"
                minPosition {{-props['wheel']['max_steering_angle']}}
                maxPosition {{props['wheel']['max_steering_angle']}}
                maxTorque {{props['wheel']['max_steering_effort']}}
                sound ""
              }
            ]
            endPoint Solid {
              name "front_right_wheel"
              children [
                USE WHEEL_SHAPE
              ]
              boundingObject USE WHEEL_SHAPE
              physics USE WHEEL_PHYSICS
            }
          }
        ]
      }
      Transform {
        translation {{vec2str(props['front_realsense']['translation'])}}
        rotation    1 0 0 {{props['front_realsense']['rotation']['pitch']}}
        children [
          RangeFinder {
            name        "front_depth_camera"
            fieldOfView {{props['front_realsense']['depth']['fov']}}
            width       {{props['front_realsense']['depth']['width']}}
            height      {{props['front_realsense']['depth']['height']}}
            maxRange    {{props['front_realsense']['depth']['max_range']}}
          }
          Camera {
            name        "front_aligned_depth_to_color_camera"
            fieldOfView {{props['front_realsense']['depth']['fov']}}
            width       {{props['front_realsense']['depth']['width']}}
            height      {{props['front_realsense']['depth']['height']}}
          }
        ]
      }
      GPS {
        name "left_gnss"
        translation {{props['gnss']['reciever_distance']/2.0}} {{props['gnss']['z']}} {{props['gnss']['x']}}
      }
      GPS {
        name "right_gnss"
        translation {{-props['gnss']['reciever_distance']/2.0}} {{props['gnss']['z']}} {{props['gnss']['x']}}
      }
    ]
    synchronization FALSE
    name            "Autonomous Twizy"
    model           "twizy"
    translation     IS translation
    rotation        IS rotation
    controller      IS controller
    controllerArgs  IS controllerArgs
    boundingObject  USE CHASSIS
  }
}
"""

# Evaluate all expressions between {{ and }} in the proto string. This is a
# poor man's verion of python3's f-strings
regex = re.compile('\{\{.*?\}\}', re.S)
parsed = re.sub(regex, lambda m: str(eval(m.group()[2:][:-2].strip())), proto)

print(parsed)
